spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lumecho?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: lumecho
  servlet:
    multipart:
      # 单个文件的最大大小 (例如：10MB)
      max-file-size: 10MB
      # 一次请求中所有文件的总大小 (例如：20MB)
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nuc.edu.lumecho.model.entity
  configuration:
    map-underscore-to-camel-case: true
