spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lumecho?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000ms

  minio:
    endpoint: http://47.116.108.205:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: lumecho

  mail:
    host: smtp.qq.com
    port: 587
    username: 2737278699@qq.com
    password: dphumjeowolodfje
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nuc.edu.lumecho.model.entity
  configuration:
    map-underscore-to-camel-case: true